/**
 * Postgres access for the `resumes` table, per docs/ARCHITECTURE.md §3.
 * Every function here takes the RLS-scoped server client from
 * `lib/supabase/server.ts` (never `lib/supabase/admin.ts`) and additionally
 * filters by `user_id` explicitly — this is the API-level half of the
 * "checked twice" ownership model in docs/ARCHITECTURE.md §2 (RLS is the
 * real guarantee; the explicit filter here lets a "no row" result collapse
 * cleanly into a `404` at the route handler instead of relying solely on
 * RLS silently returning nothing).
 *
 * Returns full DB rows (including `storage_path`, an internal detail) —
 * route handlers are responsible for shaping rows into the public response
 * types in `types/domain.ts` before returning them.
 */

import type { SupabaseClient } from "@supabase/supabase-js";

import type { Database, ResumeStatus } from "@/types/database";

type Client = SupabaseClient<Database>;
export type ResumeRow = Database["public"]["Tables"]["resumes"]["Row"];

/** Thrown when a Postgres operation on `resumes` fails unexpectedly. */
export class ResumeQueryError extends Error {
  constructor(message: string, readonly cause?: unknown) {
    super(message);
    this.name = "ResumeQueryError";
  }
}

/** Lists the caller's own resumes, ordered by `created_at desc`. */
export async function listResumesForUser(
  supabase: Client,
  userId: string,
): Promise<ResumeRow[]> {
  const { data, error } = await supabase
    .from("resumes")
    .select("*")
    .eq("user_id", userId)
    .order("created_at", { ascending: false });

  if (error) {
    throw new ResumeQueryError(
      `Failed to list resumes: ${error.message}`,
      error,
    );
  }

  return data ?? [];
}

/**
 * Fetches a single resume by id, scoped to its owner. Returns `null` if it
 * doesn't exist or isn't owned by `userId` — callers turn that into a `404`
 * (never a `403`, per docs/ARCHITECTURE.md §2, to avoid leaking existence
 * of other users' rows).
 */
export async function getResumeById(
  supabase: Client,
  userId: string,
  id: string,
): Promise<ResumeRow | null> {
  const { data, error } = await supabase
    .from("resumes")
    .select("*")
    .eq("id", id)
    .eq("user_id", userId)
    .maybeSingle();

  if (error) {
    throw new ResumeQueryError(
      `Failed to fetch resume ${id}: ${error.message}`,
      error,
    );
  }

  return data;
}

/**
 * Inserts a new `resumes` row. `id` is supplied explicitly (generated by
 * `lib/storage/resumeFiles.ts#uploadResumeFile` up front) so it matches the
 * Storage object path created for the same upload — see that module's
 * docstring for why.
 */
export async function createResume(
  supabase: Client,
  params: {
    id: string;
    userId: string;
    storagePath: string;
    fileName: string;
    fileType: string;
    fileSizeBytes: number;
    extractedText: string | null;
    status?: ResumeStatus;
  },
): Promise<ResumeRow> {
  const { data, error } = await supabase
    .from("resumes")
    .insert({
      id: params.id,
      user_id: params.userId,
      storage_path: params.storagePath,
      file_name: params.fileName,
      file_type: params.fileType,
      file_size_bytes: params.fileSizeBytes,
      extracted_text: params.extractedText,
      status: params.status ?? "uploaded",
    })
    .select("*")
    .single();

  if (error || !data) {
    throw new ResumeQueryError(
      `Failed to create resume: ${error?.message ?? "no row returned"}`,
      error,
    );
  }

  return data;
}

/**
 * Updates a resume row's mutable fields, scoped to its owner. Used by
 * `POST /api/resumes/:id/analyze` to flip `status` between
 * `'processing'` / `'analyzed'` / `'failed'` and to persist text extracted
 * from the stored file on first analysis (see
 * docs/ARCHITECTURE.md §2). Only the fields present in `patch` are sent to
 * Postgres, so e.g. passing `{ status: 'processing' }` never clobbers
 * `extracted_text`.
 */
export async function updateResume(
  supabase: Client,
  userId: string,
  id: string,
  patch: { status?: ResumeStatus; extractedText?: string | null },
): Promise<ResumeRow> {
  const update: Database["public"]["Tables"]["resumes"]["Update"] = {};
  if (patch.status !== undefined) {
    update.status = patch.status;
  }
  if (patch.extractedText !== undefined) {
    update.extracted_text = patch.extractedText;
  }

  const { data, error } = await supabase
    .from("resumes")
    .update(update)
    .eq("id", id)
    .eq("user_id", userId)
    .select("*")
    .single();

  if (error || !data) {
    throw new ResumeQueryError(
      `Failed to update resume ${id}: ${error?.message ?? "no row returned"}`,
      error,
    );
  }

  return data;
}

/**
 * Deletes a resume row, scoped to its owner. Does **not** touch the
 * Storage object — callers must delete that separately via
 * `lib/storage/resumeFiles.ts#deleteResumeFile` (see
 * `app/api/resumes/[id]/route.ts`, which deletes the Storage object first
 * so a failure there never leaves an orphaned DB row pointing at a missing
 * file).
 */
export async function deleteResume(
  supabase: Client,
  userId: string,
  id: string,
): Promise<void> {
  const { error } = await supabase
    .from("resumes")
    .delete()
    .eq("id", id)
    .eq("user_id", userId);

  if (error) {
    throw new ResumeQueryError(
      `Failed to delete resume ${id}: ${error.message}`,
      error,
    );
  }
}
